version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: ai_postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_workflows

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    container_name: ai_api

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - postgres

volumes:
  postgres_data: